export const items = [
  {
    id: 0,
    name: "Carrots",
    price: 1.5,
    image_url:
      "https://cdn11.bigcommerce.com/s-kc25pb94dz/images/stencil/1280x1280/products/271/762/Carrot__40927.1634584458.jpg?c=2",
    category: "Fresh vegetables",
    description: "Fresh and crunchy carrots.",
  },
  {
    id: 1,
    name: "Apples",
    price: 2.0,
    image_url:
      "https://www.goodfruit.com/wp-content/uploads/snowflakeApple.jpg",
    category: "Fresh fruits",
    description: "Juicy red apples.",
  },
  {
    id: 2,
    name: "Tomato Soup",
    price: 1.2,
    image_url: "https://m.media-amazon.com/images/I/61sTHchOhTL._SL1050_.jpg",
    category: "Canned foods",
    description: "Rich and savory tomato soup.",
  },
  {
    id: 3,
    name: "BBQ Sauce",
    price: 3.0,
    image_url: "https://m.media-amazon.com/images/I/71656tw3TxL.jpg",
    category: "Sauces",
    description: "Sweet and tangy BBQ sauce.",
  },
  {
    id: 4,
    name: "Pasta",
    price: 2.5,
    image_url: "https://www.budgetbytes.com/wp-content/uploads/2023/07/Bruschetta-Pasta-Overhead.jpg",
    category: "Various groceries",
    description: "High-quality pasta.",
  },
  {
    id: 5,
    name: "Basil",
    price: 0.8,
    image_url: "https://www.clickandgrow.com/cdn/shop/products/Basil_plant_1280x960_0fc95446-605c-49e3-aa42-c6f3a171b8ae.jpg",
    category: "Spices & herbs",
    description: "Fresh basil leaves.",
  },
  {
    id: 6,
    name: "Olive Oil",
    price: 5.0,
    image_url: "https://i5.walmartimages.com/seo/Great-Value-Organic-Extra-Virgin-Olive-Oil-51-fl-oz_082ffffd-d485-4261-865f-8da3e6677f0e.846f7674f455f3d595afb9e5f619ebfd.jpeg",
    category: "Oils/Vinegars",
    description: "Extra virgin olive oil.",
  },
  {
    id: 7,
    name: "Milk",
    price: 1.5,
    image_url: "https://i5.walmartimages.com/seo/Great-Value-Milk-Whole-Vitamin-D-Gallon-Plastic-Jug_6a7b09b4-f51d-4bea-a01c-85767f1b481a.86876244397d83ce6cdedb030abe6e4a.jpeg",
    category: "Refrigerated items",
    description: "Fresh organic milk.",
  },
  {
    id: 8,
    name: "Broccoli",
    price: 1.8,
    image_url:
      "https://desihalalgrocery.com/cdn/shop/products/Broccoli.jpg?v=1599368163",
    category: "Fresh vegetables",
    description: "Fresh green broccoli.",
  },
  {
    id: 9,
    name: "Bananas",
    price: 1.2,
    image_url:
      "https://www.bobtailfruit.co.uk/media/mageplaza/blog/post/4/2/42e9as7nataai4a6jcufwg.jpeg",
    category: "Fresh fruits",
    description: "Sweet ripe bananas.",
  },
  {
    id: 10,
    name: "Peas",
    price: 1.0,
    image_url: "https://www.delmonte.com/sites/default/files/Sweet%20Peas_1050x500.png",
    category: "Canned foods",
    description: "Canned green peas.",
  },
  {
    id: 11,
    name: "Ketchup",
    price: 2.0,
    image_url: "https://i5.walmartimages.com/seo/Heinz-Tomato-Ketchup-20-oz-Bottle_df19e3bc-27e9-4d72-8f83-eb86862ffb00.c02e78adf42a1c126ca71c6e0946c298.jpeg",
    category: "Sauces",
    description: "Classic tomato ketchup.",
  },
  {
    id: 12,
    name: "Rice",
    price: 3.0,
    image_url: "https://cdn.britannica.com/17/176517-050-6F2B774A/Pile-uncooked-rice-grains-Oryza-sativa.jpg",
    category: "Various groceries",
    description: "Long grain white rice.",
  },
  {
    id: 13,
    name: "Thyme",
    price: 1.0,
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Thyme-Bundle.jpg/640px-Thyme-Bundle.jpg",
    category: "Spices & herbs",
    description: "Dried thyme leaves.",
  },
  {
    id: 14,
    name: "Balsamic Vinegar",
    price: 4.0,
    image_url: "https://botticellifoods.com/cdn/shop/products/botticelli-product-vinegar-balsamic-16_9oz_1200x1200.png?v=1630688084",
    category: "Oils/Vinegars",
    description: "Aged balsamic vinegar.",
  },
  {
    id: 15,
    name: "Cheese",
    price: 3.5,
    image_url: "https://cdn.usdairy.com/optimize/getmedia/b5108b6f-59c3-4cc4-b1d5-4b9b0d1e0c54/swiss.jpg.jpg.aspx?format=webp",
    category: "Refrigerated items",
    description: "Cheddar cheese slices.",
  },
  {
    id: 16,
    name: "Spinach",
    price: 1.5,
    image_url: "https://lettuceinfo.org/wp-content/uploads/2020/09/Spinach.jpg",
    category: "Fresh vegetables",
    description: "Fresh organic spinach.",
  },
  {
    id: 17,
    name: "Oranges",
    price: 2.5,
    image_url: "https://m.media-amazon.com/images/I/61gIIgasi3L.jpg",
    category: "Fresh fruits",
    description: "Juicy and sweet oranges.",
  },
  {
    id: 18,
    name: "Corn",
    price: 1.0,
    image_url: "https://m.media-amazon.com/images/I/81nX8PngfoL.jpg",
    category: "Canned foods",
    description: "Sweet corn kernels.",
  },
  {
    id: 19,
    name: "Soy Sauce",
    price: 2.5,
    image_url: "https://kikkomanusa.com/homecooks/wp-content/uploads/2023/05/00041390000034_A1N1___15.png",
    category: "Sauces",
    description: "Salty and savory soy sauce.",
  },
];
